import {
  faMagnifyingGlass,
  faPlus,
  faHouse,
  faMap,
  faFileSignature,
  faPen,
  faChevronLeft,
  faChevronRight,
  faCheck,
  faCirclePlay,
  faXmark,
  faGaugeHigh,
  faPeopleGroup,
  faBookTanakh,
  faListCheck,
  faCirclePlus,
  faUpload,
  faEllipsis,
  faUserPlus,
  faPeopleRoof,
} from "@fortawesome/free-solid-svg-icons";

const icon = {
  faMagnifyingGlass,
  faPlus,
  faHouse,
  faMap,
  faFileSignature,
  faPen,
  faChevronLeft,
  faChevronRight,
  faCheck,
  faCirclePlay,
  faXmark,
  faGaugeHigh,
  faPeopleGroup,
  faBookTanakh,
  faListCheck,
  faCirclePlus,
  faUpload,
  faEllipsis,
  faUserPlus,
  faPeopleRoof,
};
export default icon;
